# Use the latest version of Node.js
FROM node:latest

# Set the working directory inside the container to /backend
WORKDIR /backend

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code into the /backend directory
COPY . .

# Expose the port your app will run on
EXPOSE 3000

# Start the Express app using nodemon (for development)
CMD ["nodemon", "server.js"]
